# Generated by Django 5.1.4 on 2026-05-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('fuel', 'Fuel consumption'), ('procurement', 'Procurement spend'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel night'), ('ground_transport', 'Ground transport')], max_length=24)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 (direct)'), ('2', 'Scope 2 (purchased energy)'), ('3', 'Scope 3 (value chain)')], max_length=1)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('location_code', models.CharField(blank=True, default='', max_length=64)),
                ('cost_center', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('source_ref', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('flagged', 'Flagged'), ('approved', 'Approved (locked)'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingestion.ingestionbatch')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='ingestion.rawrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='normalize_n_status_659f49_idx'), models.Index(fields=['activity_type'], name='normalize_n_activit_1f5025_idx'), models.Index(fields=['scope'], name='normalize_n_scope_7e08e2_idx'), models.Index(fields=['batch', 'status'], name='normalize_n_batch_i_5c4566_idx'), models.Index(fields=['source_ref'], name='normalize_n_source__e325ac_idx')],
            },
        ),
    ]
