# Generated by Django 5.1.4 on 2026-05-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP (fuel / procurement)'), ('utility', 'Utility (electricity)'), ('travel', 'Corporate travel')], max_length=16)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('parsing', 'Parsing'), ('ready', 'Ready for review'), ('failed', 'Failed')], default='parsing', max_length=16)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('parse_errors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['batch_id', 'row_number'],
                'indexes': [models.Index(fields=['batch', 'row_number'], name='ingestion_r_batch_i_3af63d_idx')],
            },
        ),
    ]
