# Generated by Django 5.1.4 on 2026-05-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=32)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=8)),
                ('message', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='normalize.normalizedactivity')),
            ],
            options={
                'ordering': ['activity_id', 'rule_code'],
                'indexes': [models.Index(fields=['rule_code'], name='review_acti_rule_co_b99309_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'rule_code'), name='unique_rule_per_activity')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst', models.CharField(max_length=255)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=1000)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='normalize.normalizedactivity')),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['activity', '-decided_at'], name='review_appr_activit_41fc0e_idx')],
            },
        ),
    ]
